apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80  # Exposing the application on port 80 within the cluster
      targetPort: 4499  # Port where your app is running in the container
  type: LoadBalancer  # This will expose the service externally (for cloud environments)
