name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t biswanath290/wisecow:latest .

      - name: Push Docker Image
        run: docker push biswanath290/wisecow:latest

  deploy:
    needs: build  # Waits for the build job to complete
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop wisecow-app || true
            docker rm wisecow-app || true
            docker pull your-dockerhub-username/wisecow-app:latest
            docker run -d -p 80:8080 --name wisecow-app biswanath290/wisecow:latest
